const express=require('express')
const { GetUser, InsertUser, ShowUser, DeleteUser, UpdateUser } = require('../controllers/userController')
const { GetHabitos, InsertHabitos, UpdateHabito, Showhabito, DeleteHabito, GetHabitosAll } = require('../controllers/habitoController')
const { Get_registros, Insert_registros } = require('../controllers/registro_habitosController')
const { GetMetas, InsertMetas, ShowMetas, UpdateMetas, DeleteMetas, GetMetasAll } = require('../controllers/metasController')
const { getActividades, InsetActividades, ShowActividaes, UpdateActividades, DestroyActividaes, getAllActivites } = require('../controllers/actividadesdiariasController')
const { getEmociones, InsertEmociones } = require('../controllers/emocionesController')
module.exports=router=express()

router.get("/usuarios",GetUser)
router.post('/usuarios/c',InsertUser)
router.get("/usuarios/s/:id",ShowUser)
router.put("/usuarios/u/:id",UpdateUser)
router.delete("/usuarios/d/:id",DeleteUser)
//-----------------------------------------
router.get("/habitos/a",GetHabitosAll)
router.get("/habitos/:usuario_id",GetHabitos)
router.post('/habitos/c',InsertHabitos)
router.put("/habitos/u/:id",UpdateHabito)
router.get("/habitos/s/:id",Showhabito)
router.delete("/habitos/d/:id",DeleteHabito)
//-----------------------------------------
router.get('/registros/',Get_registros)
router.post("/registros/c",Insert_registros)
//------------------------------------------
router.get("/metas/a",GetMetasAll)
router.get("/metas/:usuario_id",GetMetas)
router.post("/metas/i",InsertMetas)
router.get("/metas/s/:id",ShowMetas)
router.put("/metas/u/:id",UpdateMetas)
router.delete('/metas/d/:id',DeleteMetas)
//------------------------------------------
router.get("/actividades/a",getAllActivites)//<=> //areglar esto cambiar la rtuta a algo como /actividades/all o a
router.get("/actividades/:usuario_id",getActividades)
router.post("/actividades/i",InsetActividades)
router.get("/actividades/s/:id",ShowActividaes)
router.put("/actividades/u/:id",UpdateActividades)
router.delete("/actividades/d/:id",DestroyActividaes)
//----------------------------------------------------
router.get("/emociones",getEmociones)
router.post("/emociones/i",InsertEmociones)